### ISSUE TITLE
custom desktop file entry not working

### ISSUE THREAD

**Issue by valr337** [bakustarver/rpgmakermlinux-cicpoffs#1]
![Screenshot from 2024-04-03 21-58-01](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/165918742/bbe2aa0b-f73e-4547-8188-6e6d4aad7816)

Checked desktop entry folder
`~/.local/share/applications » ls | grep nwjs                                                                         
nwjstest.desktop
`

Some investigation.. 
I removed "#" from **Exec** entry and the desktop entry shows but a terminal appears and the program disappears
![Screenshot from 2024-04-03 22-00-26](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/165918742/b517091d-9501-466f-9d5e-61e1ad57c3d0)

To confirm its a desktop entry problem, I typed out the command the terminal 
![x3KQPC](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/165918742/aeb1e65e-7c74-4d0c-876d-f1b6523e28ed)

I tried to fix by changing the Exec line to (the commented line in install.sh)
`bash -c "/home/USER/desktopapps/nwjs/nwjs/packagefiles/nwjsstart-cicpoffs.sh" --latestnwjs --gamepath %f` as "=" is a reserved keyword but it still doesn't work 
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

OS Ubuntu 22.04 LTS
Program version `~/Downloads » rpgmaker-linux --version                                                                       
1.0.2`

**Comment by bakustarver** [comment]
Yeah, sorry, I'm using KDE plasma user so I didn't notice this bug. I also tested with openbox and it also worked. 
So I tested and tried to fix this issue in ubuntu gnome 22.04.
I would be glad if you tell me if the fix works.

**Comment by valr337** [comment]
Technically its working, however theres an error dialog box before the game starts 
![image](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/165918742/b12ed2df-dbf3-40b6-b381-2d0db210a1ea)
![image](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/165918742/539901d4-2cb7-477d-b7fe-0ba26e14bb75)

However I found the fix for v1.02 but it isnt working for the latest v1.03
Changed Exec line to 
`Exec=bash -c "/home/USER/desktopapps/nwjs/nwjs/packagefiles/nwjsstart-cicpoffs.sh --chooselatestnwjs --gamepath %f"`

**Comment by bakustarver** [comment]
yea, i forgot to remove the line with the zenity

Thanks for the test, since the bug is fixed I'm closing the thread, in the new version this window is off

**Comment by bakustarver** [comment]
yea, i forgot to remove the line with the zenity

Thanks for the test, since the bug is fixed I'm closing the thread, in the new version this window is off
