### ISSUE TITLE
[Question] how to enable gui?

### ISSUE THREAD

**Issue by silverhikari** [bakustarver/rpgmakermlinux-cicpoffs#11]
how do you display the gui as shown in the screenshots, i have attempted to do this through both the mime applauncher and via cli but neither seem to display it and there does not seem to be a argument to display it?

**Comment by silverhikari** [comment]
correction missed the rpg options in the mime luancher

**Comment by bakustarver** [comment]
you can use the $rpgmaker-linux --gui
or 
launch  “RPG Maker MV/MZ Options” application
![Знімок_20240720_053021-1](https://github.com/user-attachments/assets/45964402-abac-485b-bb25-1fbd5924b8c5)

**Comment by silverhikari** [comment]
thanks did not realize that command existed, it was not listed in the help menu.
