### ISSUE TITLE
64bit version of tyranoextract

### ISSUE THREAD

**Issue by mobedoor** [bakustarver/rpgmakermlinux-cicpoffs#13]
**Describe the bug**
I've removed 32bit libraries from my system. While the rest of the provided programs used in your scripts are 64 bit. This is the outlier.

**To Reproduce**
1. Lack 32bit libraries
2. ./tyranodataextract
3. Get `./tyranodataextract: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

**Expected behavior**
For the program to run on a 64 bit system

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Endeavour OS

**Do other games launch with the same issue?**

**Are you using the compatibility tool to run in the steam platform?**
No

**Comment by bakustarver** [comment]
Thanks for the report, I will definitely replace the executable files in the next update to 64 bit).

**Comment by bakustarver** [comment]
Fixed in the latest version, thanks.
