### ISSUE TITLE
running the installgithub.sh script to update removes and create a new nwjs folder even if it already exists

### ISSUE THREAD

**Issue by silverhikari** [bakustarver/rpgmakermlinux-cicpoffs#15]
**Describe the bug**
running the install script even if a installation exists will remove the old installation along with any node versions downloaded and install a new nwjs folder

**To Reproduce**
1. have a existing installation of '$HOME/desktopapps/nwjs'
2. add files to show diffrence in /nwjs/nwjs/nwjs
3. run install script line in the readme
4. go into nwjs files and notice back to default

**Expected behavior**
script will notice the existing installation and only update the required files such as the scripts

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Falkon
 - Version: 24.05

**Additional context**
i have not altered the path in the .config folder
![image](https://github.com/user-attachments/assets/ac898a55-d7c1-4df5-94e8-ba28b2aad9bb)
![image](https://github.com/user-attachments/assets/c9ed3aef-2963-4b93-8329-2799c79b4d8e)

**Comment by bakustarver** [comment]
This is not a bug; it is a necessity for installation and updating.

I will add the command $ rpg --updatescripts in the future, only for the scripts updates, but for now, this is the only way.
