### ISSUE TITLE
Make this wrork on Raspberry Pi

### ISSUE THREAD

**Issue by ChrisS81** [bakustarver/rpgmakermlinux-cicpoffs#17]
The current install-Script does not work on as raspberry pi 5.
I guess it has to do with aarch64-support by nw.js.
However, after some downloading everything seems fine at first, but the rpgmaker-linux - command does not work and there are many .sh-files with size = 0 bytes.

So it would be nice to have the option to create a sweet little indie-gaming rig out of as rasbpi. Renpy-Games work nicely, rpgm not so much.
As wine is not an option when using a different CPU-Arch, this scripting solution here might come in really handy for raspi users. 
Linux on x64 is fine (already tested)

Grertings,
Christ

**Comment by bakustarver** [comment]
Yes, it was a problem with the  the archiving program it was fixed after 1 day. 
if there are problems you can reinstall using this command
```
wget -qO- "https://raw.githubusercontent.com/bakustarver/rpgmakermlinux-cicpoffs/main/installgithub.sh" | bash
```
