### ISSUE TITLE
When using it as compatability tool in Steam, add option to skip the launcher.

### ISSUE THREAD

**Issue by kdliu86** [bakustarver/rpgmakermlinux-cicpoffs#18]
The launch options menu appears every time the game is launched via Steam when the RPG Maker cicpoffsmount Tool is selected as the compatability tool.  Is there a way to skip the menu?

**Comment by bakustarver** [comment]
Well, if you don't use the options quite often, you can edit the application file
"$HOME/.local/share/applications/nwjsoptions.desktop"
and remove the --gui argument
