### ISSUE TITLE
Clarification on some of the menu settings? (Steam Deck)

### ISSUE THREAD

**Issue by kdliu86** [bakustarver/rpgmakermlinux-cicpoffs#19]
What does "Show In the Menu" do?

After installation, I can leftclick/rightclick and open the RPGM game using both the mount and options entries.  But in the Steam Compatibility list only the cicpoffs mount shows up and it opens the option menu instead. #18 

How do you add jpn-locale in the options menu?

(I'm newish to Linux).

**Comment by bakustarver** [comment]
I've added an option to skip the menu in the steam to activate use
```
rpgmaker-linux --steamskipgui <true|false>     
```

I will later add the ariel font as well so that everything is automatic

**Comment by TheMSnap** [comment]
> I've added an option to skip the menu in the steam to activate use
> 
> ```
> rpgmaker-linux --steamskipgui <true|false>     
> ```
> 
> I will later add the ariel font as well

Where do I type this command? It's not recognizing the command in Konsole

**Comment by bakustarver** [comment]
activate skipping
```
rpgmaker-linux --steamskipgui true
```
deactivate skipping
```
rpgmaker-linux --steamskipgui true
```

**Comment by TheMSnap** [comment]
> activate skipping
> 
> ```
> rpgmaker-linux --steamskipgui true
> ```
> 
> deactivate skipping
> 
> ```
> rpgmaker-linux --steamskipgui false
> ```

Yes, but where? It doesn't do anything in Konsole or the Steam launcher command

**Comment by bakustarver** [comment]
If the command doesn't work, then you can use this command
```
"$HOME/desktopapps/nwjs/nwjs/packagefiles/nwjsstart-cicpoffs.sh" --steamskipgui true
```

**Comment by TheMSnap** [comment]
> If the command doesn't work, then you can use this command
> 
> ```
> "$HOME/desktopapps/nwjs/nwjs/packagefiles/nwjsstart-cicpoffs.sh" --steamskipgui true
> ```

This worked! Thanks.

**Comment by bakustarver** [comment]
If you want the rpgmaker-linux command  to run in the konsole, I need the output from these two console commands
```
cat "$HOME/.profile"
```
and 
```
ls "$HOME/.local/bin"
```

**Comment by TheMSnap** [comment]
`1)(deck@steamdeck ~)$ cat "$HOME/.profile"
cat: /home/deck/.profile: No such file or directory
(1)(deck@steamdeck ~)$ ls "$HOME/.local/bin"
rpgmaker-linux
`

**Comment by bakustarver** [comment]
Ok,i undertand, thank you very much.

**Comment by bakustarver** [comment]
@TheMSnap , you can try 
```
echo 'if [ -d "$HOME/.local/bin" ]; export PATH="$PATH:$HOME/.local/bin" ; fi' >> ~/.bash_profile
```
and then restart konsole, the command rpgmaker-linux might run successfully.

**Comment by bakustarver** [comment]
Well, with the new console command, it's fixed now
