### ISSUE TITLE
[Suggestion] RPG maker 2003 and 2000 support

### ISSUE THREAD

**Issue by SnivySquid65** [bakustarver/rpgmakermlinux-cicpoffs#23]
Installed this to play SOFTMARE_, but it won't load because it's a RPGmaker RT game.
I just want to be able to play through the LOVEWEB ARG things.  Actually, I'm trying to recompile a web only RPGmaker game from the ARG into a local playable version.  Actually, if I could get some pointers on that too, I would really appreciate it!

**Comment by bakustarver** [comment]
You are referring to RPG Maker 2003 and 2000. Currently, there is no support for these versions, but I will likely add EasyRPG Player later.

You can download the official build of EasyRPG Player from the archive, move it to the game folder, and then run it.
https://ci.easyrpg.org/job/player-linux/lastSuccessfulBuild/artifact/easyrpg-player-static.tar.gz
Your game will work.

**Comment by SnivySquid65** [comment]
Thank you so much!  I really appreciate this.  I'll keep this project in mind when playing other RPG maker games too.

**Comment by SnivySquid65** [comment]
I actually have a repository containing the files for the "web only" game I mentioned
https://github.com/SnivySquid65/manonnikki
