### ISSUE TITLE
Stuck on embedded mp4 video

### ISSUE THREAD

**Issue by Nugrud** [bakustarver/rpgmakermlinux-cicpoffs#5]
Apart from 

> wayland not detected, starting in x11
> [9280:9280:0521/191753.908190:ERROR:chrome_browser_cloud_management_controller.cc(161)] Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
> [0521/191754.037562:ERROR:elf_dynamic_array_reader.h(64)] tag not found
> [0521/191754.037627:ERROR:elf_dynamic_array_reader.h(64)] tag not found

it starts fine but is stuck on an in-game mp4 video. Is that not supported?

> 
> NWJS version - 0.29.0
> Chromium version - 65.0.3325.146
> Node version - v9.7.1
> RPG Maker Name - MV
> RPG Maker version - 1.6.1
> 
> ffmpeg prebuild link
> https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/releases/tag/0.29.0

**Comment by bakustarver** [comment]
Can you at least write the name of the game.
and preferably also share your save at the moment of the error.

**Comment by Nugrud** [comment]
I've gathered it's a "modified", not clean, rpg maker engine game, so I guess it's not up to bakustarver's support. Thanks for the answer anyway.

**Comment by bakustarver** [comment]
So, I'm closing this thread. You can describe in the details modifications related to the engine in your game in another topic.
