### ISSUE TITLE
Black screen when trying to launch OMORI

### ISSUE THREAD

**Issue by gatenosix** [bakustarver/rpgmakermlinux-cicpoffs#7]
For some reason, I'm unable to launch OMORI using this tool.

Whenever I try to do so, the game window appears but it's just a black screen:

![image](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/6661236/b098a149-c555-4423-93d9-3bd82ff9be0f)

It works fine if I use Proton Experimental to run the game however, and the startup logo and menu appear as expected.

I'm using an AMD GPU (7900xt) and running the game via Wayland.

Here is the console output:

> (yad:13318): Gdk-CRITICAL **: 13:36:48.712: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
> FALSE FALSE  FALSE v0.84.0 FALSE FALSE  FALSE     FALSE FALSE           
> Finished
> Uninstalling the text hooker plugin
> The text hooker plugin is not installed
> /home/xero/desktopapps/nwjs/nwjs/cicpoffs /home/xero/.local/share/Steam/steamapps/common/OMORI/www /home/xero/desktopapps/nwjs/nwjs/nwjs/nwjs-v0.84.0-linux-x64/www
> Mounting done.
> Total time: 0 seconds
> wayland detected
> [13407:13407:0604/133653.159536:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
> [0604/133653.172396:ERROR:elf_dynamic_array_reader.h(64)] tag not found
> [13447:13522:0604/133653.250705:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE

Would be grateful for any advice/assistance - thank you!

**Comment by bakustarver** [comment]
Fortunately, the Omori developers made the limitations that the game would work only on Windows or Mac
I found a repository with patches for [JoiPlay](https://github.com/einstein95/omori-joiplay) and modified them a little for linux.
[omori-patches.zip](https://github.com/user-attachments/files/15585824/omori-patches.zip)
