### ISSUE TITLE
Failed to call method: org.freedesktop.ScreenSaver.GetActive

### ISSUE THREAD

**Issue by loongemperor** [bakustarver/rpgmakermlinux-cicpoffs#9]
using linux mint debian, every game fails with seemingly the same error:
`[9888:9888:0628/111510.197357:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented`
after that it just gets stuck on a blank screen.

I looked around a bit, and this seems to be a common bug in many programs in many distros.
which happens when a program is trying to interface with the screensaver via dbus to see if the screen is available or not.

for example here:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/632

the script then hangs if the reply is `this method is not implemented` instead of the expected replies of true/false?

system config:
https://termbin.com/wlso

**Comment by bakustarver** [comment]
I tested the rpg maker mv/mz engine games in lmde 6 using Virtual box and the games worked fine for me. 

Here's for example a toga game from itch.io.
https://kikaba.itch.io/toga


![1](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/66978329/f1e990f4-32c9-49a1-8452-781537dd66a0)
![2](https://github.com/bakustarver/rpgmakermlinux-cicpoffs/assets/66978329/9423ba4c-054d-4e92-bfaf-57df7449e018)

**Comment by israfiel-a** [comment]
I've gotten this error message running some games, but it never kills the program; simply hangs it for a moment and then continues.

**Comment by loongemperor** [comment]
> I tested the rpg maker mv/mz games in lmde 6 using Virtual box and the games worked fine for me.

Alright, thank you.
It is likely that something is wrong specifically with my system then.
I have been banging my head against it and could not fix it though.

That said, I think it would be a nice improvement if the program could just ignore it when the screensaver DBUS is unresponsive.

**Comment by bakustarver** [comment]
This is an nwjs bug, you should probably write a report here.
https://github.com/nwjs/nw.js/issues

Specifying: System, Version of nwjs, your display server protocol: wayland or xorg and the log of this error.
You can also upload your system config report.

I also have some errors with dbus, but the games are running successfully.


You can also post your report with the system config.
I also have errors with dbus, but the games are running successfully.

**Comment by bakustarver** [comment]
I don't compile the nwjs manually, I download it from the official site, so I can't fix this problem, you can report it to the developers at the github link.
https://github.com/nwjs/nw.js/issues

**Comment by SauceyRed** [comment]
I found a solution that works for me:
1. Run the game using the SDK version of nwjs
2. When the window opens to a blank screen, right-click and click on "Reload app".
3. Game works

**Comment by loongemperor** [comment]
I never managed to get the GUI to work. but I did find a workaround.

I went to
`/home/username/Templates`

created an executable file called
`game-rpgmaker-linux.sh`

which is a text file whose contents say
```
#!/bin/bash
rpgmaker-linux
```

in every RPGM game I right click next to "game.exe" and select creating a new file and picking the `game-rpgmaker-linux.sh`. which then adds it there. I can then double click that file to successfully run RPGM games via cicpoffs

I completely gave up on running using the "open with" gui dialog. although it can be used for upgrading
